spring:
  tmdb:
    api-key: ${TMDB_API_KEY}
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_webapp
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google: # Google OAuth2 클라이언트 설정
            client-id: ${GOOGLE_CLIENT_ID} # Google 클라이언트 ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # Google 클라이언트 시크릿
            redirect-uri: "{baseUrl}/login/oauth2/code/google" # Google 인증 후 리디렉션 URL
            scope: email, profile # Google OAuth2 요청 범위 (email과 profile 정보 요청)
#          naver: # Naver OAuth2 클라이언트 설정
#            client-id: [NAVER_CLIENT_ID] # Naver 클라이언트 ID
#            client-secret: [NAVER_CLIENT_SECRET] # Naver 클라이언트 시크릿
#            redirect-uri: "{baseUrl}/login/oauth2/code/naver" # Naver 인증 후 리디렉션 URL
#            scope: name, email # Naver OAuth2 요청 범위 (이름과 이메일 정보 요청)
#          kakao: # Kakao OAuth2 클라이언트 설정
#            client-id: [KAKAO_CLIENT_ID] # Kakao 클라이언트 ID
#            client-secret: [KAKAO_CLIENT_SECRET] # Kakao 클라이언트 시크릿
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # Kakao 인증 후 리디렉션 URL
#            client-name: Kakao # Kakao 클라이언트 이름 (식별용)
#            authorization-grant-type: authorization_code # 인증 방식 (authorization_code 방식 사용)
#            scope: profile_nickname, account_email # Kakao OAuth2 요청 범위 (닉네임과 이메일 정보 요청)
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
#          naver: # Naver OAuth2 제공자 설정
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize # Naver 인증 URL
#            token-uri: https://nid.naver.com/oauth2.0/token # Naver 토큰 요청 URL
#            user-info-uri: https://openapi.naver.com/v1/nid/me # Naver 사용자 정보 요청 URL
#            user-name-attribute: response # 사용자 이름 속성 (Naver의 사용자 정보 JSON 구조에 따라 설정)
#          kakao: # Kakao OAuth2 제공자 설정
#            authorization-uri: https://kauth.kakao.com/oauth/authorize # Kakao 인증 URL
#            token-uri: https://kauth.kakao.com/oauth/token # Kakao 토큰 요청 URL
#            user-info-uri: https://kapi.kakao.com/v2/user/me # Kakao 사용자 정보 요청 URL
#            user-name-attribute: id # 사용자 이름 속성 (Kakao의 사용자 정보 JSON 구조에 따라 설정)
